import streamlit as st
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import pandas as pd
import numpy as np
import io
import contextlib
import sys

# --- 1. SYSTEM CONFIGURATION ---
st.set_page_config(page_title="Jarvis Analysis Hub", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
    <style>
    .main { background-color: #0e1117; color: white; }
    .stButton>button { width: 100%; border-radius: 5px; background-color: #1e1e26; color: #00d4ff; border: 1px solid #00d4ff; }
    .stButton>button:hover { background-color: #00d4ff; color: #000000; }
    </style>
    """, unsafe_allow_html=True)

with st.sidebar:
    st.title("🛰️ Jarvis System")
    st.info("Awaiting script upload for processing.")

# --- 2. MAIN DASHBOARD ---
st.title("📥 Universal Code & Plot Hub")
st.write("Upload any Python script. The system will automatically intercept `plt.show()` or Plotly `fig` objects and render them here.")

uploaded_file = st.file_uploader("Drop a .py script here", type=['py'])

if uploaded_file is not None:
    st.subheader(f"Executing: {uploaded_file.name}")
    
    # Read the uploaded Python code
    code = uploaded_file.getvalue().decode("utf-8")
    
    # Create buffers and namespaces for the sandbox execution
    output_buffer = io.StringIO()
    sandbox_namespace = {}
    
    # --- 3. EXECUTION SANDBOX ---
    try:
        # Redirect standard output (print statements) to our buffer
        with contextlib.redirect_stdout(output_buffer):
            # Run the code!
            exec(code, globals(), sandbox_namespace)
        
        # Display any print() outputs from the script
        terminal_output = output_buffer.getvalue()
        if terminal_output:
            st.text_area("Terminal Output", terminal_output, height=150)
            
        st.success("Execution Complete. Scanning for plots...")
        
        # --- 4. AUTO-PLOT DETECTION ---
        
        # Detection A: Matplotlib Figures
        # Grabs any figure generated by the script before it closes
        fig_nums = plt.get_fignums()
        if fig_nums:
            for i in fig_nums:
                fig = plt.figure(i)
                st.pyplot(fig)
                plt.close(fig) # Clean up memory
                
        # Detection B: Plotly Figures
        # Checks if the script created a variable named 'fig' that is a Plotly object
        for var_name, var_value in sandbox_namespace.items():
            if isinstance(var_value, (go.Figure)):
                st.plotly_chart(var_value, use_container_width=True)
                
    except Exception as e:
        st.error(f"System Error during execution: {e}")
